// export.js — Export utilities: email digest, clipboard, markdown download

/** Format briefing as clean plain-text email digest. */
export function toBriefingText(briefing) {
  const lines = [];
  lines.push(`GITHUB INTELLIGENCE STATION — MORNING BRIEF`);
  lines.push(`${briefing.briefing_date} · Signal: ${briefing.signal_quality.toUpperCase()} · ${briefing.total_scanned} repos scanned`);
  lines.push('');
  lines.push('EXECUTIVE SUMMARY');
  lines.push('─'.repeat(60));
  lines.push(briefing.executive_summary);
  lines.push('');
  lines.push('TOP PICKS');
  lines.push('─'.repeat(60));
  briefing.top_picks.forEach(pick => {
    lines.push(`\n${pick.rank}. ${pick.headline}`);
    lines.push(`   Workflow: ${pick.primary_workflow.toUpperCase()} · Urgency: ${pick.urgency.toUpperCase()}`);
    lines.push(`   Why now: ${pick.why_now}`);
    lines.push(`   → Action: ${pick.action}`);
    lines.push(`   Repo: https://github.com/${pick.repo_id}`);
  });
  if (briefing.skip_list?.length) {
    lines.push('\nSKIP THIS CYCLE');
    lines.push('─'.repeat(60));
    briefing.skip_list.forEach(s => lines.push(`• ${s.repo_id}: ${s.reason}`));
  }
  lines.push('\n' + '─'.repeat(60));
  lines.push('The Intelligence Station · github.com/Thesoulofsuccess/github-intel-station');
  return lines.join('\n');
}

/** Format briefing as Markdown for Notion/Obsidian. */
export function toMarkdown(briefing) {
  const lines = [];
  lines.push(`# Morning Brief — ${briefing.briefing_date}`);
  lines.push(`> **Signal:** ${briefing.signal_quality} · **Scanned:** ${briefing.total_scanned} repos`);
  lines.push('');
  lines.push('## Executive Summary');
  lines.push(briefing.executive_summary);
  lines.push('');
  lines.push('## Top Picks');
  briefing.top_picks.forEach(pick => {
    lines.push(`\n### ${pick.rank}. ${pick.headline}`);
    lines.push(`**Workflow:** \`${pick.primary_workflow}\` · **Urgency:** \`${pick.urgency}\``);
    lines.push(`**Why now:** ${pick.why_now}`);
    lines.push(`**→ Action:** ${pick.action}`);
    lines.push(`**Repo:** [${pick.repo_id}](https://github.com/${pick.repo_id})`);
  });
  lines.push('\n---');
  lines.push('*Generated by The Intelligence Station*');
  return lines.join('\n');
}

/** Copy text to clipboard — works on mobile too. */
export async function copyToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    const el = document.createElement('textarea');
    el.value = text;
    el.style.cssText = 'position:fixed;opacity:0;top:0;left:0';
    document.body.appendChild(el);
    el.focus(); el.select();
    const ok = document.execCommand('copy');
    document.body.removeChild(el);
    return ok;
  }
}

/** Trigger a .txt or .md download. */
export function downloadText(text, filename) {
  const blob = new Blob([text], { type: 'text/plain' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}
